using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Main.Migrator.Migrations
{
    /// <inheritdoc />
    public partial class CatalogueCandidateIdUpdate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "supplier_products_catalogue_candidate_id_fk",
                schema: "catalogue_enrichment",
                table: "supplier_products");

            migrationBuilder.Sql(
                """
                ALTER TABLE catalogue_enrichment.catalogue_candidates
                    ALTER COLUMN id DROP IDENTITY IF EXISTS;

                ALTER TABLE catalogue_enrichment.catalogue_candidates
                    ALTER COLUMN id TYPE uuid
                    USING (
                        '00000000-0000-0000-0000-' ||
                        lpad(id::text, 12, '0')
                    )::uuid;

                ALTER TABLE catalogue_enrichment.supplier_products
                    ALTER COLUMN catalogue_candidate_id TYPE uuid
                    USING CASE
                        WHEN catalogue_candidate_id IS NULL THEN NULL
                        ELSE (
                            '00000000-0000-0000-0000-' ||
                            lpad(catalogue_candidate_id::text, 12, '0')
                        )::uuid
                    END;
                """);

            migrationBuilder.AddForeignKey(
                name: "supplier_products_catalogue_candidate_id_fk",
                schema: "catalogue_enrichment",
                table: "supplier_products",
                column: "catalogue_candidate_id",
                principalSchema: "catalogue_enrichment",
                principalTable: "catalogue_candidates",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "supplier_products_catalogue_candidate_id_fk",
                schema: "catalogue_enrichment",
                table: "supplier_products");

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM catalogue_enrichment.catalogue_candidates
                        WHERE id::text !~ '^00000000-0000-0000-0000-[0-9]{12}$'
                    ) THEN
                        RAISE EXCEPTION 'Catalogue candidate UUIDs created after this migration cannot be converted back to integer IDs';
                    END IF;
                END $$;

                ALTER TABLE catalogue_enrichment.supplier_products
                    ALTER COLUMN catalogue_candidate_id TYPE integer
                    USING CASE
                        WHEN catalogue_candidate_id IS NULL THEN NULL
                        ELSE right(catalogue_candidate_id::text, 12)::integer
                    END;

                ALTER TABLE catalogue_enrichment.catalogue_candidates
                    ALTER COLUMN id TYPE integer
                    USING right(id::text, 12)::integer;

                ALTER TABLE catalogue_enrichment.catalogue_candidates
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

                SELECT setval(
                    pg_get_serial_sequence(
                        'catalogue_enrichment.catalogue_candidates',
                        'id'),
                    COALESCE((
                        SELECT MAX(id)
                        FROM catalogue_enrichment.catalogue_candidates
                    ), 1),
                    EXISTS (
                        SELECT 1
                        FROM catalogue_enrichment.catalogue_candidates
                    ));
                """);

            migrationBuilder.AddForeignKey(
                name: "supplier_products_catalogue_candidate_id_fk",
                schema: "catalogue_enrichment",
                table: "supplier_products",
                column: "catalogue_candidate_id",
                principalSchema: "catalogue_enrichment",
                principalTable: "catalogue_candidates",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
