using MassTransit;
using MassTransit.EntityFrameworkCoreIntegration;
using Microsoft.EntityFrameworkCore;
using Pricing.Entities;

namespace Pricing.Persistence.Contexts;

public partial class DContext : DbContext
{
    public DContext()
    {
    }

    public DContext(DbContextOptions<DContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MarkupGroup> MarkupGroups { get; set; }

    public virtual DbSet<MarkupRange> MarkupRanges { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.AddOutboxMessageEntity();
        modelBuilder.AddOutboxStateEntity();
        modelBuilder.AddInboxStateEntity();

        modelBuilder.Entity<OutboxMessage>().ToTable("OutboxMessage", "msg");
        modelBuilder.Entity<OutboxState>().ToTable("OutboxState", "msg");
        modelBuilder.Entity<InboxState>().ToTable("InboxState", "msg");
        
        modelBuilder.Entity<MarkupGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("markup_group_pk");

            entity.ToTable("markup_group");

            entity.HasIndex(e => e.CurrencyId, "IX_markup_group_currency_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CurrencyId).HasColumnName("currency_id");
            entity.Property(e => e.IsAutoGenerated).HasColumnName("is_auto_generated");
            entity.Property(e => e.Name).HasColumnName("name");
        });

        modelBuilder.Entity<MarkupRange>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("markup_ranges_pk");

            entity.ToTable("markup_ranges");

            entity.HasIndex(e => e.GroupId, "IX_markup_ranges_group_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.Markup).HasColumnName("markup");
            entity.Property(e => e.RangeEnd).HasColumnName("range_end");
            entity.Property(e => e.RangeStart).HasColumnName("range_start");

            entity.HasOne(d => d.Group).WithMany(p => p.MarkupRanges)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("markup_ranges_markup_group_id_fk");
        });

        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.Key).HasName("settings_pk");

            entity.ToTable("settings");

            entity.Property(e => e.Key).HasColumnName("key");
            entity.Property(e => e.Value).HasColumnName("value");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
