using Contracts.Models.ArticleCoefficients;
using Mapster;
using Pricing.Abstractions.Dtos.Markups;
using Pricing.Abstractions.Models;
using Pricing.Abstractions.Models.Pricing;
using Pricing.Entities;

namespace Pricing.Application.Configs;

public static class Mapster
{
    public static void Configure()
    {
        TypeAdapterConfig<Contracts.Models.Currency.Currency, Currency>.NewConfig()
            .Map(dest => dest.Id, src => src.Id)
            .Map(dest => dest.ToUsdRate, src => src.ToUsdRate);
        
        //Markup

        TypeAdapterConfig<MarkupGroup, MarkupGroupDto>.NewConfig()
            .IgnoreNonMapped(true)
            .Map(dest => dest.Id, src => src.Id)
            .Map(dest => dest.Name, src => src.Name)
            .Map(dest => dest.CurrencyId, src => src.CurrencyId)
            .Map(dest => dest.IsAutoGenerated, src => src.IsAutoGenerated);

        TypeAdapterConfig<MarkupRange, MarkupRangeDto>.NewConfig()
            .IgnoreNonMapped(true)
            .Map(dest => dest.Id, src => src.Id)
            .Map(dest => dest.MarkupRate, src => src.Markup)
            .Map(dest => dest.RangeEnd, src => src.RangeEnd)
            .Map(dest => dest.RangeStart, src => src.RangeStart);

        TypeAdapterConfig<NewMarkupRangeDto, MarkupRange>.NewConfig()
            .IgnoreNonMapped(true)
            .Map(dest => dest.Markup, src => src.MarkupRate)
            .Map(dest => dest.RangeEnd, src => src.RangeEnd)
            .Map(dest => dest.RangeStart, src => src.RangeStart);
        
        TypeAdapterConfig<ArticleCoefficient, PriceCoefficient>.NewConfig()
            .Map(dest => dest.Name, src => src.Coefficient.Name)
            .Map(dest => dest.Order, src => src.Coefficient.Order)
            .Map(dest => dest.Value, src => src.Coefficient.Value)
            .Map(dest => dest.Type, src => src.Coefficient.Type)
            .Map(dest => dest.ValidTill, src => src.ValidTill);
    }
}