<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LocanDefaultCulture>en</LocanDefaultCulture>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Abstractions\Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Locan.Generator" Version="1.0.6" />
    </ItemGroup>

    <ItemGroup>
        <LocanResource Include="Localization/**/*.json"
                       GenerateMessages="true"
                       CopyToOutput="false" />
    </ItemGroup>
</Project>
