using System.Text.Json.Serialization;

namespace Pricing.Application.Dtos.Markup;

public record MarkupGroupDto
{
    [JsonPropertyName("id")]
    public required int Id { get; init; }

    [JsonPropertyName("name")]
    public required string? Name { get; init; }

    [JsonPropertyName("currencyId")]
    public required int CurrencyId { get; init; }

    [JsonPropertyName("autoGenerated")]
    public required bool IsAutoGenerated { get; init; }

    [JsonPropertyName("ranges")]
    public required IEnumerable<MarkupRangeDto> Ranges { get; init; }
}