services:
  main-api:
    image: ${ARTIFACT_REGISTRY_HOST}/main-api:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/main-api:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/main-api:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/main-api:buildcache,mode=min

  search-api:
    image: ${ARTIFACT_REGISTRY_HOST}/search-api:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/search-api:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/search-api:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/search-api:buildcache,mode=min

  pricing-api:
    image: ${ARTIFACT_REGISTRY_HOST}/pricing-api:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/pricing-api:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/pricing-api:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/pricing-api:buildcache,mode=min

  gateway:
    image: ${ARTIFACT_REGISTRY_HOST}/gateway:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/gateway:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/gateway:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/gateway:buildcache,mode=min

  analytics-api:
    image: ${ARTIFACT_REGISTRY_HOST}/analytics-api:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/analytics-api:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/analytics-api:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/analytics-api:buildcache,mode=min

  analytics-worker:
    image: ${ARTIFACT_REGISTRY_HOST}/analytics-worker:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/analytics-worker:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/analytics-worker:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/analytics-worker:buildcache,mode=min

  main-worker:
    image: ${ARTIFACT_REGISTRY_HOST}/main-worker:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/main-worker:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/main-worker:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/main-worker:buildcache,mode=min

  pgql:
    image: ${ARTIFACT_REGISTRY_HOST}/postgres-cron:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/postgres-cron:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/postgres-cron:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/postgres-cron:buildcache,mode=min
