services:
  analytics.migrator:
    image: ${ARTIFACT_REGISTRY_HOST}/analytics-migrator:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/analytics-migrator:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/analytics-migrator:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/analytics-migrator:buildcache,mode=min

  main.migrator:
    image: ${ARTIFACT_REGISTRY_HOST}/main-migrator:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/main-migrator:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/main-migrator:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/main-migrator:buildcache,mode=min

  pricing.migrator:
    image: ${ARTIFACT_REGISTRY_HOST}/pricing-migrator:${IMAGE_TAG}
    build:
      tags:
        - ${ARTIFACT_REGISTRY_HOST}/pricing-migrator:${IMAGE_TAG}
      cache_from:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/pricing-migrator:buildcache
      cache_to:
        - type=registry,ref=${ARTIFACT_REGISTRY_HOST}/pricing-migrator:buildcache,mode=min
