global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "main-api"
    metrics_path: /metrics
    static_configs:
      - targets: [ "main-api:8080" ]

  - job_name: "pricing-api"
    metrics_path: /metrics
    static_configs:
      - targets: [ "pricing-api:8080" ]

  - job_name: "analytics-api"
    metrics_path: /metrics
    static_configs:
      - targets: [ "analytics-api:8080" ]

  - job_name: "search-api"
    metrics_path: /metrics
    static_configs:
      - targets: [ "search-api:8080" ]

  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: [ "gateway:8080" ]
