using Application.Common.Interfaces.Settings;
using Contracts.Analytics;
using MassTransit;
using MediatR;
using Pricing.Application.Dtos.Markup;
using Pricing.Application.Handlers.Markup.UpsertMarkupGroup;
using Pricing.Entities.Settings;

namespace Pricing.Application.Consumers;

public class MarkupAnalyzedConsumer(
    ISender sender,
    ISettingsService settingsService) : IConsumer<MarkupAnalyzedEvent>
{
    public async Task Consume(ConsumeContext<MarkupAnalyzedEvent> context)
    {
        if (context.Message.Ranges.Count == 0) return;
        
        var baseCurrencyId = (await settingsService.GetOrDefault<CurrencySetting>())
            .Data.BaseCurrencyId;
        
        await sender.Send(
            new UpsertMarkupGroupCommand(
                new UpsertMarkupGroupDto
                {
                    Name = "Auto Generated Markup",
                    CurrencyId = baseCurrencyId,
                    Ranges = context.Message.Ranges
                        .Select(x => new UpsertMarkupRangeDto
                        {
                            RangeStart = x.FromCost,
                            RangeEnd = x.ToCost,
                            Markup = x.MeanMarkup
                        })
                        .ToList()
                },
                IsAutoGenerated: true),
            context.CancellationToken);

        await context.Publish(new MarkupRangesRefreshRequestedEvent(), context.CancellationToken);
    }
}
