// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pricing.Persistence.Contexts;

#nullable disable

namespace Pricing.Migrator.Migrations
{
    [DbContext(typeof(DContext))]
    [Migration("20260708144824_UpdIdx")]
    partial class UpdIdx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.CommonEntities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Key")
                        .HasName("settings_pk");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("pricing.entities.settings.pricingsetting_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("pricing.entities.settings.pricingsetting_who_updated_idx");

                    b.ToTable("settings", (string)null);

                    b.HasDiscriminator<string>("Key").HasValue("Setting");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "msg");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "msg");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "msg");
                });

            modelBuilder.Entity("Pricing.Entities.MarkupGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_generated");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Id")
                        .HasName("markup_group_pk");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("pricing.entities.markupgroup_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("pricing.entities.markupgroup_who_updated_idx");

                    b.HasIndex(new[] { "CurrencyId" }, "IX_markup_group_currency_id");

                    b.ToTable("markup_group", (string)null);
                });

            modelBuilder.Entity("Pricing.Entities.MarkupRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<decimal>("Markup")
                        .HasColumnType("numeric")
                        .HasColumnName("markup");

                    b.Property<decimal>("RangeEnd")
                        .HasColumnType("numeric")
                        .HasColumnName("range_end");

                    b.Property<decimal>("RangeStart")
                        .HasColumnType("numeric")
                        .HasColumnName("range_start");

                    b.HasKey("Id")
                        .HasName("markup_ranges_pk");

                    b.HasIndex(new[] { "GroupId" }, "IX_markup_ranges_group_id");

                    b.ToTable("markup_ranges", (string)null);
                });

            modelBuilder.Entity("Pricing.Entities.PriceOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<int>("DaysToRefund")
                        .HasColumnType("integer")
                        .HasColumnName("days_to_refund");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryProbability")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_probability");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GuaranteedDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guaranteed_delivery_date");

                    b.Property<int>("MinimumPurchaseQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_purchase_quantity");

                    b.Property<string>("OfferForStorage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("offer_for_storage");

                    b.Property<DateTime>("OrderTill")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_till");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityCoefficient")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_coefficient");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Id")
                        .HasName("price_offer_pk");

                    b.HasAlternateKey("Source", "SourceKey", "OfferForStorage")
                        .HasName("price_offer_source_source_key_uq");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("pricing.entities.priceoffer_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("pricing.entities.priceoffer_who_updated_idx");

                    b.HasIndex(new[] { "CurrencyId" }, "price_offer_currency_id_index");

                    b.HasIndex(new[] { "ExpiresAt" }, "price_offer_expires_at_index");

                    b.HasIndex(new[] { "OfferForStorage" }, "price_offer_offer_for_storage_index");

                    b.HasIndex(new[] { "ProductId", "OfferForStorage" }, "price_offer_product_id_index");

                    b.ToTable("price_offers", (string)null);
                });

            modelBuilder.Entity("Pricing.Entities.Settings.CurrencySetting", b =>
                {
                    b.HasBaseType("Domain.CommonEntities.Setting");

                    b.HasDiscriminator().HasValue("CurrencySetting");
                });

            modelBuilder.Entity("Pricing.Entities.Settings.PricingSetting", b =>
                {
                    b.HasBaseType("Domain.CommonEntities.Setting");

                    b.HasDiscriminator().HasValue("PricingSettings");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Pricing.Entities.MarkupRange", b =>
                {
                    b.HasOne("Pricing.Entities.MarkupGroup", "Group")
                        .WithMany("MarkupRanges")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("markup_ranges_markup_group_id_fk");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Pricing.Entities.MarkupGroup", b =>
                {
                    b.Navigation("MarkupRanges");
                });
#pragma warning restore 612, 618
        }
    }
}
