// ReSharper disable InconsistentNaming
namespace Main.Enums;

public enum PermissionCodes
{
    // ===== ARTICLES =====
    ARTICLES_CREATE,
    ARTICLES_EDIT,
    ARTICLES_DELETE,
    ARTICLES_GET_FULL,
    ARTICLES_GET_MAIN,

    // ===== PRODUCERS =====
    PRODUCERS_CREATE,
    PRODUCERS_EDIT,
    PRODUCERS_DELETE,

    // ===== ARTICLE / CHARACTERISTICS =====
    ARTICLE_CHARACTERISTICS_CREATE,
    ARTICLE_CHARACTERISTICS_UPDATE,
    ARTICLE_CHARACTERISTICS_DELETE,

    // ===== ARTICLE / CROSSES =====
    ARTICLE_CROSSES_GET,
    ARTICLE_CROSSES_CREATE,
    ARTICLE_CROSSES_DELETE,

    // ===== ARTICLE / CONTENT =====
    ARTICLE_CONTENT_CREATE,
    ARTICLE_CONTENT_DELETE,
    ARTICLE_CONTENT_EDIT,

    // ===== ARTICLE / PAIR =====
    ARTICLE_PAIR_CREATE,
    ARTICLE_PAIR_EDIT,
    ARTICLE_PAIR_DELETE,

    // ===== ARTICLE / IMAGES =====
    ARTICLE_IMAGES_CREATE,
    ARTICLE_IMAGES_DELETE,

    // ===== ARTICLE / RESERVATIONS =====
    ARTICLE_RESERVATIONS_CREATE,
    ARTICLE_RESERVATIONS_DELETE,
    ARTICLE_RESERVATIONS_EDIT,
    ARTICLE_RESERVATIONS_GET_ME,
    ARTICLE_RESERVATIONS_GET_ALL,

    // ===== BALANCES / TRANSACTION =====
    BALANCES_TRANSACTION_CREATE,
    BALANCES_TRANSACTION_DELETE,
    BALANCES_TRANSACTION_EDIT,
    BALANCES_TRANSACTION_GET_ME,
    BALANCES_TRANSACTION_GET_ALL,

    // ===== CURRENCIES =====
    CURRENCIES_CREATE,
    CURRENCIES_GET,

    // ===== MARKUP =====
    MARKUP_CREATE,
    MARKUP_DELETE,
    MARKUP_GET,
    MARKUP_SET_DEFAULT,

    // ===== PRICES =====
    PRICES_GET_DETAILED,
    PRICES_GET_STANDARD,

    // ===== PURCHASE =====
    PURCHASE_CREATE,
    PURCHASE_DELETE,
    PURCHASE_EDIT,
    PURCHASE_GET,

    // ===== ROLES =====
    ROLES_CREATE,
    ROLES_GET,
    ROLES_PERMISSIONS_CREATE,

    // ===== SALES =====
    SALES_CREATE,
    SALES_DELETE,
    SALES_EDIT,
    SALES_GET,

    // ===== STORAGES =====
    STORAGES_CREATE,
    STORAGES_DELETE,
    STORAGES_EDIT,
    STORAGES_GET,

    STORAGES_CONTENT_CREATE,
    STORAGES_CONTENT_DELETE,
    STORAGES_CONTENT_EDIT,
    STORAGES_CONTENT_GET_STANDARD,
    STORAGES_CONTENT_GET_ALL,

    // ===== STORAGES =====
    STORAGE_ROUTES_GET,
    STORAGE_ROUTES_CREATE,
    STORAGE_ROUTES_EDIT,
    STORAGE_ROUTES_DELETE,
    // ===== USERS =====
    USERS_CREATE,
    USERS_GET,
    USERS_INFO_GET,
    USERS_DISCOUNT_CREATE,
    USERS_DISCOUNT_GET,
    USERS_MAILS_CREATE,
    USERS_PERMISSIONS_CREATE,
    USERS_VEHICLES_CREATE_ME,
    USERS_VEHICLES_CREATE_ALL,
    USERS_STORAGES_ADD,
    USERS_STORAGES_GET,

    // ===== PERMISSIONS =====
    PERMISSIONS_CREATE,
    PERMISSIONS_GET,
    
    // ===== CART =====
    CART_ADD,
    CART_GET,
    CART_DELETE,
    CART_UPDATE,
    
    // ===== OPTIONS =====
    OPTIONS_GET,
}
