<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Locan.Generator" Version="1.0.6"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Exceptions\Exceptions.csproj"/>
        <ProjectReference Include="..\Search.Entities\Search.Entities.csproj"/>
        <ProjectReference Include="..\Search.Enums\Search.Enums.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <LocanResource Include="Localization/**/*.json"
                       GenerateMessages="true"
                       CopyToOutput="false"/>
    </ItemGroup>

</Project>
