// <auto-generated />
using System;
using Analytics.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Migrator.Migrations
{
    [DbContext(typeof(DContext))]
    partial class DContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("ToUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("to_usd");

                    b.HasKey("Id")
                        .HasName("currencies_pk");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.MetricCalculationJob", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("MetricId")
                        .HasColumnType("uuid")
                        .HasColumnName("metric_id");

                    b.Property<string>("MetricSystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("metric_system_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("RequestId")
                        .HasName("request_id_pk");

                    b.HasIndex(new[] { "CreateAt" }, "metrics_calc_jobs_created_at_index");

                    b.HasIndex(new[] { "MetricId" }, "metrics_calc_jobs_metric_id_index")
                        .IsUnique();

                    b.HasIndex(new[] { "Status", "MetricSystemName" }, "metrics_calc_jobs_status_name_index");

                    b.ToTable("metric_calculation_jobs", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<long>("DependsOn")
                        .HasColumnType("bigint")
                        .HasColumnName("depends_on");

                    b.Property<byte[]>("DimensionHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("dimension_hash");

                    b.Property<string>("DimensionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dimension_key");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Json")
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<DateTime>("RangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_end");

                    b.Property<DateTime>("RangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_start");

                    b.Property<DateTime?>("RecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at");

                    b.Property<long>("Tags")
                        .HasColumnType("bigint")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("metrics_pk");

                    b.HasIndex(new[] { "CreatedAt" }, "metrics_created_at_index");

                    b.HasIndex(new[] { "CreatedBy" }, "metrics_created_by_index");

                    b.HasIndex(new[] { "CurrencyId" }, "metrics_currency_id_index");

                    b.HasIndex(new[] { "Discriminator" }, "metrics_dirty_index")
                        .HasFilter("(tags & 1) = 1");

                    b.HasIndex(new[] { "DependsOn", "RangeStart", "RangeEnd" }, "metrics_range_depends_index");

                    b.HasIndex(new[] { "Discriminator", "RangeStart", "RangeEnd", "DimensionHash" }, "metrics_range_start_end_discriminator_u_index")
                        .IsUnique();

                    b.ToTable("metrics", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Metric");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Analytics.Entities.PurchaseContent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PurchaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purchase_id");

                    b.HasKey("Id")
                        .HasName("purchase_contents_pk");

                    b.HasIndex(new[] { "ArticleId" }, "purchase_contents_article_id_index");

                    b.HasIndex(new[] { "PurchaseId" }, "purchase_contents_purchase_id_index");

                    b.ToTable("purchase_contents", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.PurchasesFact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sum");

                    b.HasKey("Id")
                        .HasName("purchases_fact_pk");

                    b.HasIndex(new[] { "CreatedAt" }, "purchases_fact_created_at_index");

                    b.HasIndex(new[] { "CurrencyId" }, "purchases_fact_currency_id_index");

                    b.HasIndex(new[] { "SupplierId" }, "purchases_fact_supplier_id_index");

                    b.ToTable("purchases_fact", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.SaleContent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("SaleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("sale_contents_pk");

                    b.HasIndex(new[] { "ArticleId" }, "sale_contents_article_id_index");

                    b.HasIndex(new[] { "SaleId" }, "sale_contents_sale_id_index");

                    b.ToTable("sale_contents", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.SaleContentDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("buy_price");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.HasKey("Id")
                        .HasName("sale_content_detail_pk");

                    b.HasIndex(new[] { "CurrencyId" }, "sale_content_detail_currency_id_index");

                    b.ToTable("sale_content_detail", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.SalesFact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sum");

                    b.HasKey("Id")
                        .HasName("sales_fact_pk");

                    b.HasIndex(new[] { "BuyerId" }, "sales_fact_buyer_id_index");

                    b.HasIndex(new[] { "CreatedAt" }, "sales_fact_created_at_index");

                    b.HasIndex(new[] { "CurrencyId" }, "sales_fact_currency_id_index");

                    b.ToTable("sales_fact", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "msg");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "msg");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "msg");
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.ArticleSalesMetric", b =>
                {
                    b.HasBaseType("Analytics.Entities.Metrics.Metric");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.HasIndex(new[] { "Discriminator", "ArticleId" }, "metrics_discriminator_article_index");

                    b.HasDiscriminator().HasValue("ArticleSalesMetric");
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.Metric", b =>
                {
                    b.HasOne("Analytics.Entities.Currency", "Currency")
                        .WithMany("Metrics")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("metrics_currencies_id_fk");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Analytics.Entities.PurchaseContent", b =>
                {
                    b.HasOne("Analytics.Entities.PurchasesFact", "Purchase")
                        .WithMany("PurchaseContents")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_contents_purchases_fact_id_fk");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Analytics.Entities.PurchasesFact", b =>
                {
                    b.HasOne("Analytics.Entities.Currency", "Currency")
                        .WithMany("PurchasesFacts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("purchases_fact_currencies_id_fk");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Analytics.Entities.SaleContent", b =>
                {
                    b.HasOne("Analytics.Entities.SalesFact", "Sale")
                        .WithMany("SaleContents")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("sale_contents_sales_fact_id_fk");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Analytics.Entities.SaleContentDetail", b =>
                {
                    b.HasOne("Analytics.Entities.Currency", "Currency")
                        .WithMany("SaleContentDetails")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("sale_content_detail_currencies_id_fk");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Analytics.Entities.SalesFact", b =>
                {
                    b.HasOne("Analytics.Entities.Currency", "Currency")
                        .WithMany("SalesFacts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("sales_fact_currencies_id_fk");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Analytics.Entities.Currency", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("PurchasesFacts");

                    b.Navigation("SaleContentDetails");

                    b.Navigation("SalesFacts");
                });

            modelBuilder.Entity("Analytics.Entities.PurchasesFact", b =>
                {
                    b.Navigation("PurchaseContents");
                });

            modelBuilder.Entity("Analytics.Entities.SalesFact", b =>
                {
                    b.Navigation("SaleContents");
                });
#pragma warning restore 612, 618
        }
    }
}
