// <auto-generated />
using System;
using Analytics.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Migrator.Migrations
{
    [DbContext(typeof(DContext))]
    partial class DContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "dblink");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Entities.Metrics.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<long>("DependsOn")
                        .HasColumnType("bigint")
                        .HasColumnName("depends_on");

                    b.Property<string>("DimensionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dimension_key");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Json")
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<byte[]>("NaturalKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("natural_key");

                    b.Property<DateTime>("RangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_end");

                    b.Property<DateTime>("RangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_start");

                    b.Property<DateTime?>("RecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at");

                    b.Property<long>("Tags")
                        .HasColumnType("bigint")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Id")
                        .HasName("metrics_pk");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("analytics.entities.metrics.productsalesmetric_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("analytics.entities.metrics.productsalesmetric_who_updated_idx");

                    b.HasIndex(new[] { "CurrencyId" }, "metrics_currency_id_index");

                    b.HasIndex(new[] { "Discriminator" }, "metrics_dirty_index")
                        .HasFilter("(tags & 1) = 1");

                    b.HasIndex(new[] { "NaturalKey" }, "metrics_natural_key_index")
                        .IsUnique();

                    b.HasIndex(new[] { "DependsOn", "RangeStart", "RangeEnd" }, "metrics_range_depends_index");

                    b.ToTable("metrics", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Metric");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.MetricJob", b =>
                {
                    b.Property<Guid>("MetricId")
                        .HasColumnType("uuid")
                        .HasColumnName("metric_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.HasKey("MetricId", "JobId")
                        .HasName("metric_jobs_pk");

                    b.HasIndex(new[] { "JobId" }, "metric_jobs_job_id_idx");

                    b.HasIndex(new[] { "MetricId" }, "metric_jobs_metric_id_idx");

                    b.ToTable("metric_jobs", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.PurchaseContent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.HasKey("Id")
                        .HasName("purchase_contents_pk");

                    b.HasIndex(new[] { "ProductId" }, "purchase_contents_product_id_index");

                    b.HasIndex(new[] { "PurchaseId" }, "purchase_contents_purchase_id_index");

                    b.ToTable("purchase_contents", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.PurchasesFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sum");

                    b.HasKey("Id")
                        .HasName("purchases_fact_pk");

                    b.HasIndex(new[] { "CreatedAt" }, "purchases_fact_created_at_index");

                    b.HasIndex(new[] { "CurrencyId" }, "purchases_fact_currency_id_index");

                    b.HasIndex(new[] { "SupplierId" }, "purchases_fact_supplier_id_index");

                    b.ToTable("purchases_fact", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.SaleContent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("PriceInBaseCurrency")
                        .HasColumnType("numeric")
                        .HasColumnName("price_in_base_currency");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<Guid>("SaleId")
                        .HasMaxLength(128)
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("sale_contents_pk");

                    b.HasIndex(new[] { "ProductId" }, "sale_contents_product_id_index");

                    b.HasIndex(new[] { "SaleId" }, "sale_contents_sale_id_index");

                    b.ToTable("sale_contents", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.SaleContentDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("buy_price");

                    b.Property<decimal>("BuyPriceInBaseCurrency")
                        .HasColumnType("numeric")
                        .HasColumnName("buy_price_in_base_currency");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<int>("SaleContentId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_content_id");

                    b.HasKey("Id")
                        .HasName("sale_content_detail_pk");

                    b.HasIndex(new[] { "CurrencyId" }, "sale_content_detail_currency_id_index");

                    b.HasIndex(new[] { "SaleContentId" }, "sale_content_detail_sale_content_id_index");

                    b.ToTable("sale_content_detail", (string)null);
                });

            modelBuilder.Entity("Analytics.Entities.SalesFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("base_currency_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sum");

                    b.HasKey("Id")
                        .HasName("sales_fact_pk");

                    b.HasIndex(new[] { "BuyerId" }, "sales_fact_buyer_id_index");

                    b.HasIndex(new[] { "CreatedAt" }, "sales_fact_created_at_index");

                    b.HasIndex(new[] { "CurrencyId" }, "sales_fact_currency_id_index");

                    b.ToTable("sales_fact", (string)null);
                });

            modelBuilder.Entity("Domain.CommonEntities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseHolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_holder_id");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("system_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Id")
                        .HasName("jobs_pk");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("domain.commonentities.job_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("domain.commonentities.job_who_updated_idx");

                    b.HasIndex(new[] { "LockedAt" }, "jobs_locked_at_idx");

                    b.HasIndex(new[] { "Status", "Id" }, "jobs_status_id_idx");

                    b.HasIndex(new[] { "SystemName" }, "jobs_system_name_idx");

                    b.ToTable("jobs", "job");
                });

            modelBuilder.Entity("Domain.CommonEntities.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cron");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("InputState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_state");

                    b.Property<string>("JobSystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_system_name");

                    b.Property<DateTime?>("LastQueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_queued_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Id")
                        .HasName("job_schedules_pk");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("domain.commonentities.jobschedule_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("domain.commonentities.jobschedule_who_updated_idx");

                    b.HasIndex(new[] { "Enabled", "NextRunAt", "Id" }, "job_schedules_enabled_next_run_at_id_idx");

                    b.HasIndex(new[] { "JobSystemName" }, "job_schedules_job_system_name_idx");

                    b.HasIndex(new[] { "Name" }, "job_schedules_name_idx");

                    b.ToTable("job_schedules", "job");
                });

            modelBuilder.Entity("Domain.CommonEntities.JobScheduleRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("JobScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_schedule_id");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id")
                        .HasName("job_schedule_runs_pk");

                    b.HasIndex(new[] { "JobId" }, "job_schedule_runs_job_id_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "JobScheduleId", "ScheduledAt" }, "job_schedule_runs_job_schedule_id_scheduled_at_idx")
                        .IsUnique();

                    b.ToTable("job_schedule_runs", "job");
                });

            modelBuilder.Entity("Domain.CommonEntities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WhoCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_created");

                    b.Property<Guid?>("WhoUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("who_updated");

                    b.HasKey("Key")
                        .HasName("settings_pk");

                    b.HasIndex("WhoCreated")
                        .HasDatabaseName("domain.commonentities.setting_who_created_idx");

                    b.HasIndex("WhoUpdated")
                        .HasDatabaseName("domain.commonentities.setting_who_updated_idx");

                    b.ToTable("settings", (string)null);

                    b.HasDiscriminator<string>("Key").HasValue("Setting");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "msg");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "msg");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "msg");
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.ProductPurchasesMetric", b =>
                {
                    b.HasBaseType("Analytics.Entities.Metrics.Metric");

                    b.Property<int>("ProductId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasIndex(new[] { "Discriminator", "ProductId" }, "metrics_discriminator_article_index");

                    b.HasDiscriminator().HasValue("ProductPurchasesMetric");
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.ProductSalesMetric", b =>
                {
                    b.HasBaseType("Analytics.Entities.Metrics.Metric");

                    b.Property<int>("ProductId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasIndex(new[] { "Discriminator", "ProductId" }, "metrics_discriminator_article_index");

                    b.HasDiscriminator().HasValue("ProductSalesMetric");
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.MetricJob", b =>
                {
                    b.HasOne("Domain.CommonEntities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("metric_jobs_job_id_fk");

                    b.HasOne("Analytics.Entities.Metrics.Metric", "Metric")
                        .WithMany("Jobs")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("metric_jobs_metric_id_fk");

                    b.Navigation("Job");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Analytics.Entities.PurchaseContent", b =>
                {
                    b.HasOne("Analytics.Entities.PurchasesFact", "Purchase")
                        .WithMany("PurchaseContents")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_contents_purchases_fact_id_fk");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Analytics.Entities.SaleContent", b =>
                {
                    b.HasOne("Analytics.Entities.SalesFact", "Sale")
                        .WithMany("SaleContents")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sale_contents_sales_fact_id_fk");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Analytics.Entities.SaleContentDetail", b =>
                {
                    b.HasOne("Analytics.Entities.SaleContent", "SaleContent")
                        .WithMany("Details")
                        .HasForeignKey("SaleContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sale_content_detail_sale_content_id_fk");

                    b.Navigation("SaleContent");
                });

            modelBuilder.Entity("Domain.CommonEntities.JobScheduleRun", b =>
                {
                    b.HasOne("Domain.CommonEntities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_schedule_runs_job_id_fk");

                    b.HasOne("Domain.CommonEntities.JobSchedule", null)
                        .WithMany("Runs")
                        .HasForeignKey("JobScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_schedule_runs_job_schedule_id_fk");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Analytics.Entities.Metrics.Metric", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Analytics.Entities.PurchasesFact", b =>
                {
                    b.Navigation("PurchaseContents");
                });

            modelBuilder.Entity("Analytics.Entities.SaleContent", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Analytics.Entities.SalesFact", b =>
                {
                    b.Navigation("SaleContents");
                });

            modelBuilder.Entity("Domain.CommonEntities.JobSchedule", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
