namespace Main.Core.Entities;

public partial class MarkupGroup
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public bool IsAutoGenerated { get; set; }

    public int CurrencyId { get; set; }

    public virtual Currency Currency { get; set; } = null!;

    public virtual ICollection<MarkupRange> MarkupRanges { get; set; } = new List<MarkupRange>();
}
