using BulkValidation.Core.Attributes;
using Domain;
using Domain.Extensions;

namespace Pricing.Entities;

public class MarkupGroup : AuditableEntity<MarkupGroup, int>
{
    private readonly List<MarkupRange> _markupRanges = [];

    private MarkupGroup()
    {
    }

    private MarkupGroup(
        string? name,
        int currencyId,
        IEnumerable<MarkupRange> markupRanges,
        bool isAutoGenerated = false)
    {
        Name = name;
        CurrencyId = currencyId;
        IsAutoGenerated = isAutoGenerated;
        ReplaceRanges(markupRanges);
    }

    [Validate]
    public int Id { get; private set; }

    public string? Name { get; private set; }

    public bool IsAutoGenerated { get; private set; }

    public int CurrencyId { get; private set; }

    public IReadOnlyCollection<MarkupRange> MarkupRanges => _markupRanges;

    public static MarkupGroup Create(
        string? name,
        int currencyId,
        IEnumerable<MarkupRange> markupRanges)
    {
        return new MarkupGroup(name, currencyId, markupRanges);
    }

    public static MarkupGroup CreateGenerated(
        int currencyId,
        IEnumerable<MarkupRange> markupRanges)
    {
        return new MarkupGroup(
            "Auto Generated Markup",
            currencyId,
            markupRanges,
            true);
    }

    public void SetCurrencyId(int currencyId)
    {
        CurrencyId = currencyId;
    }

    public void ReplaceRanges(IEnumerable<MarkupRange> markupRanges)
    {
        ArgumentNullException.ThrowIfNull(markupRanges);
        var ranges = markupRanges.ToList();
        ranges.AgainstEmpty(() => new InvalidOperationException("Markup ranges are not empty"));

        _markupRanges.Clear();
        _markupRanges.AddRange(ranges);
    }

    public override int GetId()
    {
        return Id;
    }
}