<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BulkValidation.Core" Version="1.0.9"/>
        <PackageReference Include="BulkValidation.SourceGeneration" Version="1.0.5"/>
        <PackageReference Include="Locan.Generator" Version="1.0.6"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Abstractions\Abstractions.csproj"/>
        <ProjectReference Include="..\..\..\Core\Domain\Domain.csproj"/>
        <ProjectReference Include="..\..\..\Core\Exceptions\Exceptions.csproj"/>
        <ProjectReference Include="..\..\..\Infrastructure\SchemaGeneration\SchemaGeneration.Abstractions\SchemaGeneration.Abstractions.csproj"/>
        <ProjectReference Include="..\Pricing.Enums\Pricing.Enums.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <LocanResource Include="Localization/**/*.json"
                       GenerateMessages="true"
                       CopyToOutput="false"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Exceptions\PriceApplier\"/>
    </ItemGroup>

</Project>
