using Application.Common.Interfaces.Currency;
using Application.Common.Interfaces.Repositories;
using Application.Common.Interfaces.Settings;
using Internal.Integration.Core.Interfaces.Main;
using Microsoft.EntityFrameworkCore;
using Pricing.Application.Interfaces;
using Pricing.Entities;
using Pricing.Entities.Settings;

namespace Pricing.Application.Services.Markup;

public class MarkupInitializer(
    IMarkupContainer container,
    IReadRepository<MarkupGroup, int> repository,
    ISettingsService settingsService,
    IMainClient mainClient,
    ICurrencyConverter currencyConverter,
    ICurrencyRatesProvider ratesProvider
) : IMarkupInitializer
{
    public async Task Initialize(CancellationToken cancellationToken = default)
    {
        var pricingSettings = await settingsService.GetOrDefault<PricingSetting>(cancellationToken);

        var query = pricingSettings.Data.SelectedMarkupId == null
            ? repository.Query
                .OrderByDescending(x => x.CreatedAt)
                .Where(x => x.IsAutoGenerated)
            : repository.Query
                .Where(x => x.Id == pricingSettings.Data.SelectedMarkupId);

        var defaultGroup = await query
                               .Include(x => x.MarkupRanges)
                               .FirstOrDefaultAsync(cancellationToken)
                           ?? throw new InvalidOperationException(
                               "Unable initialize markup service, Markup group not found.");

        var allCurrencies = await mainClient
            .CurrencyNode
            .GetCurrencies(cancellationToken);

        if (!allCurrencies.Success)
            throw new InvalidOperationException(
                $"Unable initialize markup service, currencies not found. {allCurrencies.Error}");

        if (await ratesProvider.GetRateOrDefault(defaultGroup.CurrencyId, cancellationToken) == null)
            throw new InvalidOperationException(
                $"Unable initialize markup service, currency rate not found. CurrencyId: {defaultGroup.CurrencyId}");

        var otherCurrencies = new Dictionary<int, IEnumerable<MarkupRange>>();

        foreach (var currency in allCurrencies.ValueOrThrow
                     .Where(x => x.Id != defaultGroup.CurrencyId))
        {
            if (await ratesProvider.GetRateOrDefault(currency.Id, cancellationToken) == null) continue;

            var list = new List<MarkupRange>();
            foreach (var range in defaultGroup.MarkupRanges)
            {
                var start = await currencyConverter.ConvertAsync(
                    range.RangeStart,
                    defaultGroup.CurrencyId,
                    currency.Id,
                    cancellationToken);

                var end = await currencyConverter.ConvertAsync(
                    range.RangeEnd,
                    defaultGroup.CurrencyId,
                    currency.Id,
                    cancellationToken);

                list.Add(
                    MarkupRange.Create(
                        start,
                        end,
                        range.Markup));
            }

            otherCurrencies[currency.Id] = list;
        }

        container.Initialize(
            defaultGroup.CurrencyId,
            new Models.Markup(pricingSettings.Data.DefaultMarkup),
            defaultGroup.MarkupRanges,
            otherCurrencies);
    }
}