using Abstractions.Interfaces.Persistence;
using Application.Common.Interfaces.Cqrs;
using Application.Common.Interfaces.Repositories;
using Attributes;
using MediatR;
using Pricing.Application.Dtos.Markup;
using Pricing.Entities;
using Pricing.Entities.Exceptions.Markup;

namespace Pricing.Application.Handlers.Markup.UpsertMarkupGroup;

[Transactional]
[AutoSave]
public record UpsertMarkupGroupCommand(
    UpsertMarkupGroupDto MarkupGroup,
    bool IsAutoGenerated = false
) : ICommand;

public class UpsertMarkupGroupHandler(
    IRepository<MarkupGroup, int> repository,
    IUnitOfWork unitOfWork
) : ICommandHandler<UpsertMarkupGroupCommand>
{
    public async Task<Unit> Handle(UpsertMarkupGroupCommand request, CancellationToken cancellationToken)
    {
        var ranges = request.MarkupGroup.Ranges
            .Select(x => MarkupRange.Create(
                x.RangeStart,
                x.RangeEnd,
                x.Markup))
            .ToList();

        if (request.MarkupGroup.Id is null)
        {
            await unitOfWork.AddAsync(
                MarkupGroup.Create(
                    request.MarkupGroup.Name,
                    request.MarkupGroup.CurrencyId,
                    ranges,
                    request.IsAutoGenerated),
                cancellationToken);

            return Unit.Value;
        }

        var criteria = Criteria<MarkupGroup>.New()
            .Where(x => x.Id == request.MarkupGroup.Id)
            .Include(x => x.MarkupRanges)
            .Track()
            .Build();

        var group = await repository.FirstOrDefaultAsync(criteria, cancellationToken)
                    ?? throw new MarkupGroupNotFoundException(request.MarkupGroup.Id.Value);

        group.Update(
            request.MarkupGroup.Name,
            request.MarkupGroup.CurrencyId,
            ranges,
            request.IsAutoGenerated);

        return Unit.Value;
    }
}