using Abstractions.Interfaces.Services;
using Application.Common.Interfaces;
using Application.Common.Interfaces.Cqrs;
using Application.Common.Interfaces.Repositories;
using Application.Common.Interfaces.Settings;
using Attributes;
using Contracts.Markup;
using MediatR;
using Pricing.Abstractions.Dtos.Markups;
using Pricing.Entities;

namespace Pricing.Application.Handlers.Markups.SetGeneratedMarkup;

[Transactional]
public record SetGeneratedMarkupCommand(IEnumerable<NewMarkupRangeDto> Ranges, int CurrencyId) : ICommand;

public class SetGeneratedMarkupHandler(
    ISettingsService settingsService,
    IRepository<MarkupGroup, int> repository,
    IUnitOfWork unitOfWork,
    IIntegrationEventScope integrationEventScope) : ICommandHandler<SetGeneratedMarkupCommand>
{
    public async Task<Unit> Handle(SetGeneratedMarkupCommand request, CancellationToken cancellationToken)
    {
        var criteria = Criteria<MarkupGroup>.New()
            .Track()
            .Where(x => x.CurrencyId == request.CurrencyId && x.IsAutoGenerated)
            .Build();
        var generatedMarkup = await repository.FirstOrDefaultAsync(criteria, cancellationToken);

        var ranges = request
            .Ranges
            .Select(x => MarkupRange.Create(
                x.RangeStart,
                x.RangeEnd,
                x.MarkupRate));
        
        if (generatedMarkup == null)
        {
            generatedMarkup = MarkupGroup.CreateGenerated(
                request.CurrencyId,
                ranges);

            await unitOfWork.AddAsync(generatedMarkup, cancellationToken);
        }
        else
        {
            generatedMarkup.SetCurrencyId(request.CurrencyId);
            generatedMarkup.ReplaceRanges(ranges);
        }
        

        if (setting.SelectedMarkupId == generatedMarkup.Id)
            await publishEndpoint.Publish(new MarkupGroupChangedEvent { GroupId = generatedMarkup.Id },
                cancellationToken);

        await unitOfWork.SaveChangesAsync(cancellationToken);
        return Unit.Value;
    }
}
