using Abstractions.Models;
using Application.Common.Extensions;
using Application.Common.Interfaces.Cqrs;
using Application.Common.Interfaces.Repositories;
using LinqKit;
using Microsoft.EntityFrameworkCore;
using Pricing.Application.Dtos.Markup;
using Pricing.Entities;

namespace Pricing.Application.Handlers.Markup.GetMarkups;

public record GetMarkupsQuery(
    Pagination Pagination) : IQuery<GetMarkupsResult>;

public record GetMarkupsResult(IReadOnlyList<MarkupGroupDto> Groups);

public class GetMarkupsHandler(
    IReadRepository<MarkupGroup, int> repository
    ) : IQueryHandler<GetMarkupsQuery, GetMarkupsResult>
{
    public async Task<GetMarkupsResult> Handle(GetMarkupsQuery request, CancellationToken cancellationToken)
    {
        var result = await repository.Query
            .AsExpandable()
            .Select(x => new MarkupGroupDto
            {
                Id = x.Id,
                CurrencyId = x.CurrencyId,
                Name = x.Name,
                IsAutoGenerated = x.IsAutoGenerated,
                Ranges = x.MarkupRanges.Select(z => new MarkupRangeDto
                {
                    Markup = z.Markup,
                    Id = z.Id,
                    RangeStart = z.RangeStart,
                    RangeEnd = z.RangeEnd
                })
            })
            .ApplyPagination(request.Pagination)
            .ToListAsync(cancellationToken);
        
        return new GetMarkupsResult(result);
    }
}