namespace Pricing.Abstractions.Dtos.Markups;

public class MarkupGroupDto
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public bool IsAutoGenerated { get; set; }

    public int CurrencyId { get; set; }

    public string CurrencySign { get; set; } = null!;
}